// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt2C7WK8AxnSZIUdgwO42_6te16EppOkY',
    appId: '1:974422701776:web:a43275bf16b7b0181b90d5',
    messagingSenderId: '974422701776',
    projectId: 'polaris-chief-mate-93c44',
    authDomain: 'polaris-chief-mate-93c44.firebaseapp.com',
    databaseURL: 'https://polaris-chief-mate-93c44-default-rtdb.firebaseio.com',
    storageBucket: 'polaris-chief-mate-93c44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDniqqe_pt7SU3GcsHZ1ahdIrOiQtpGjC4',
    appId: '1:974422701776:android:233d17a5ca8d77621b90d5',
    messagingSenderId: '974422701776',
    projectId: 'polaris-chief-mate-93c44',
    databaseURL: 'https://polaris-chief-mate-93c44-default-rtdb.firebaseio.com',
    storageBucket: 'polaris-chief-mate-93c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDClgpVjPHYvB3XViwM9gdY8vMNghY4eMc',
    appId: '1:974422701776:ios:b96e38774a77aacf1b90d5',
    messagingSenderId: '974422701776',
    projectId: 'polaris-chief-mate-93c44',
    databaseURL: 'https://polaris-chief-mate-93c44-default-rtdb.firebaseio.com',
    storageBucket: 'polaris-chief-mate-93c44.appspot.com',
    androidClientId: '974422701776-91t43dgch1iht838lo9m4nn7p1ceduc6.apps.googleusercontent.com',
    iosClientId: '974422701776-7l4pbppdcp97u2gabquad4gdla9csltg.apps.googleusercontent.com',
    iosBundleId: 'com.example.polarisChiefMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDClgpVjPHYvB3XViwM9gdY8vMNghY4eMc',
    appId: '1:974422701776:ios:b96e38774a77aacf1b90d5',
    messagingSenderId: '974422701776',
    projectId: 'polaris-chief-mate-93c44',
    databaseURL: 'https://polaris-chief-mate-93c44-default-rtdb.firebaseio.com',
    storageBucket: 'polaris-chief-mate-93c44.appspot.com',
    androidClientId: '974422701776-91t43dgch1iht838lo9m4nn7p1ceduc6.apps.googleusercontent.com',
    iosClientId: '974422701776-7l4pbppdcp97u2gabquad4gdla9csltg.apps.googleusercontent.com',
    iosBundleId: 'com.example.polarisChiefMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt2C7WK8AxnSZIUdgwO42_6te16EppOkY',
    appId: '1:974422701776:web:72384ead56631c441b90d5',
    messagingSenderId: '974422701776',
    projectId: 'polaris-chief-mate-93c44',
    authDomain: 'polaris-chief-mate-93c44.firebaseapp.com',
    databaseURL: 'https://polaris-chief-mate-93c44-default-rtdb.firebaseio.com',
    storageBucket: 'polaris-chief-mate-93c44.appspot.com',
  );

}